### ISSUE TITLE
Incompatible with python 3.7, breaks Azure CLI

### ISSUE THREAD

**Issue by maximbaz** [Microsoft/ApplicationInsights-Python#121]
For example:

```
❯ az aks get-versions --location westeurope
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/azure/cli/__main__.py", line 14, in <module>
    import azure.cli.core.telemetry as telemetry
  File "/usr/lib/python3.7/site-packages/azure/cli/core/telemetry.py", line 20, in <module>
    import azure.cli.core.telemetry_upload as telemetry_core
  File "/usr/lib/python3.7/site-packages/azure/cli/core/telemetry_upload.py", line 20, in <module>
    from applicationinsights import TelemetryClient
  File "/usr/lib/python3.7/site-packages/applicationinsights/__init__.py", line 1, in <module>
    from .TelemetryClient import TelemetryClient
  File "/usr/lib/python3.7/site-packages/applicationinsights/TelemetryClient.py", line 5, in <module>
    from applicationinsights import channel
  File "/usr/lib/python3.7/site-packages/applicationinsights/channel/__init__.py", line 7, in <module>
    from .TelemetryChannel import TelemetryChannel
  File "/usr/lib/python3.7/site-packages/applicationinsights/channel/TelemetryChannel.py", line 6, in <module>
    from .TelemetryContext import TelemetryContext
  File "/usr/lib/python3.7/site-packages/applicationinsights/channel/TelemetryContext.py", line 4, in <module>
    from applicationinsights.channel import contracts
  File "/usr/lib/python3.7/site-packages/applicationinsights/channel/contracts/__init__.py", line 7, in <module>
    from .RemoteDependencyData import RemoteDependencyData
  File "/usr/lib/python3.7/site-packages/applicationinsights/channel/contracts/RemoteDependencyData.py", line 256
    def async(self):
            ^
SyntaxError: invalid syntax
```

This is because python 3.7 was recently released, and [async and await are now reserved keywords](https://docs.python.org/3/whatsnew/3.7.html).

Please also enable check for 3.7 on Travis 😉

**Comment by maximbaz** [comment]
My bad, the version of this package in the package distribution I used was 0.11.1, the issue is not present in 0.11.5.
