### ISSUE TITLE
AI Python SDK inside a docker container doesn't send

### ISSUE THREAD

**Issue by khilscher** [microsoft/ApplicationInsights-Python#67]
Using applicationinsights==0.11.1
Docker container running on Windows Nano.

When my python code runs outside of a docker container, I can use tc.flush() and everything works fine and messages are received by AI. 

Take the same Python app and run it inside a Windows docker container, tc.flush() causes the app to hang. No messages are received by AI.

Commenting out tc.flush()  causes the Python app to run fine inside the docker container, but no messages are received by AI. E.g.
```
tc.track_event('Solver start', { 'jobid': jobid })
#tc.flush()
```

**Comment by FunksMaName** [comment]
The Python SDK is now on version 0.11.7, 6 whole months in and it's still the same old story with this bug when running on "windowsservercore:ltsc2016" docker images, as usual, well played Microsoft.

**Comment by SergeyKanzhelev** [comment]
@Reyang can you take a look? If you plan to re-use this channel in OC - you will likely hit this issue

**Comment by reyang** [comment]
Thanks @SergeyKanzhelev. I don't plan to re-use the channel.

**Comment by sachin-ac** [comment]
The bug is occurring here due to SSL certificate exception:
[](https://github.com/Microsoft/ApplicationInsights-Python/blob/0e8342023f79e422cb718ade544bc34af9baf6d3/applicationinsights/channel/SenderBase.py#L136)
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

This is a known issue with Python in Windows Docker container:
[](https://bugs.python.org/issue36137)

The prescribed temporary workaround which worked for me was the following:
certutil -generateSSTFromWU roots.sst && certutil -addstore -f root roots.sst && del roots.sst

**Comment by madelineliao** [comment]
Hi @reyang, I'm running into the same issue on Docker; `tc.flush()` hangs on forever. 

Is there any solution for this? The request never seems to time out.

When I force exit the program, I get the following output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/applicationinsights/channel/SenderBase.py", line 136, in send
    response = HTTPClient.urlopen(request, timeout=self._timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
```

followed by:
```
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/hydrate/__main__.py", line 82, in <module>
    main()
  File "/app/hydrate/__main__.py", line 78, in main
    telemetry.flush()
  File "/app/hydrate/telemetry.py", line 84, in flush
    self._telemetry_client.flush()
  File "/usr/local/lib/python3.7/site-packages/applicationinsights/TelemetryClient.py", line 59, in flush
    self._channel.flush()
  File "/usr/local/lib/python3.7/site-packages/applicationinsights/channel/TelemetryChannel.py", line 73, in flush
    self._queue.flush()
  File "/usr/local/lib/python3.7/site-packages/applicationinsights/channel/SynchronousQueue.py", line 31, in flush
    local_sender.send(data)
  File "/usr/local/lib/python3.7/site-packages/applicationinsights/channel/SenderBase.py", line 136, in send
    response = HTTPClient.urlopen(request, timeout=self._timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
```

Thank you!
